collections_config:
  data:
    path: src/data
    output: false
    icon: settings
    items:
      - name: footer
        path: footer.json
        parser: json

paths:
  static: public
  uploads: public/uploads
  images: public/images

_inputs:
  src:
    type: image
    comment: Select an image

timezone: Africa/Cairo
markdown:
  engine: commonmark
  options:
    gfm: true
